title: Eduvis
name: Eduvis
description: >-
  Eduvis, a not-for-profit organisation providing educational strategies for blind and vision
  (visually) impaired students taking up studies in mathematics and physical education within
  higher education.  Founded by Charlie Roberts.  Provides funding for accessible calculators,
  research and development of accessible CAS software calculators and presentations as a
  resource for VI students on available CAS solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eduvis.com.au" # the base hostname & protocol for your site, e.g. http://example.com

# SCSS
sass:
  style: compressed

# Build settings
theme: texture
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Texture theme settings
texture:
  title: Eduvis
  tagline: Education strategies for visually impaired students
  date_format: "%b %-d, %Y"
  style: custom
  analytics_id: "G-CEDD9NZJKK"

  social_links:
    twitter: placeholder
    github: eduvis
    linkedIn: in/placeholder

  showNav: true

  navigation:
    - title: Home
      url: "/"
    - title: About
      url: "/about"
    - title: Team
      url: "/team"
    - title: Projects
      url: "/projects"
    - title: Testimonials
      url: "/testimonials"
    - title: Links
      url: "/links"
    - title: Contact
      url: "/contact"

environment: prod
