title: Eduvis
name: Eduvis
Author: Eduvis
email: charlie@eduvis.com
description: >-
  Eduvis, a not-for-profit organisation providing educational strategies for blind and vision
  (visually) impaired students taking up studies in mathematics and physical education within
  higher education.  Founded by Charlie Roberts.  Provides funding for accessible calculators,
  research and development of accessible CAS software calculators and presentations as a
  resource for VI students on available CAS solutions.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: # the subpath of your site, e.g. /blog
url: "http://eduvis.com.au" # the base hostname & protocol for your site, e.g. http://example.com

# SCSS
sass:
  sass_dir: _sass
  style: compressed

permalink: /posts/:title/

# Texture theme settings
texture:
  title: Eduvis
  tagline: Education strategies for visually impaired students
  date_format: "%b %-d, %Y"
  style: custom
  analytics_id: "G-CEDD9NZJKK"

  social_links:
    github: eduvis
    linkedIn: in/charlie-roberts-97505455

  showNav: true
  showPicker: false

header_pages:
  - title: Home
    url: "/"
  - title: About
    url: "/about"
  - title: Team
    url: "/team"
  - title: Projects
    url: "/projects"
  - title: Testimonials
    url: "/testimonials"
  - title: Links
    url: "/links"
  - title: Contact
    url: "/contact"

# Build settings
remote_theme: samarsault/texture
theme: texture
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

environment: prod
