title: Eduvis
name: Eduvis
Author: Eduvis
email: charlie@eduvis.com
description: Learning strategies for visually impaired students.
show_excerpts: true
url: "http://eduvis.com.au"
google_analytics: G-CEDD9NZJKK

# SCSS
sass:
  sass_dir: _sass
  style: compressed

nav:
  - title: Home
    url: "/"
  - title: About
    url: "/about"
  - title: Team
    url: "/team"
  - title: Projects
    url: "/projects"
  - title: Testimonials
    url: "/testimonials"
  - title: Links
    url: "/links"
  - title: Contact
    url: "/contact"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

environment: prod
