title: Eduvis
name: EduVis
description: >-
  Eduvis, a not-for-profit organisation providing educational strategies for blind and vision
  (visually) impaired students taking up studies in mathematics and physical education within
  higher education.  Founded by Charlie Roberts.  Provides funding for accessible calculators,
  research and development of accessible CAS software calculators and presentations as a
  resource for VI students on available CAS solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eduvis.com.au" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Specific appearance and order of navigation links
header_pages:
  - index.md
  - about.md
  - team.md
  - projects.md
  - maple-2022-cheat-sheet.md
  - testimonials.md
  - links.md
  - contact.md

environment: prod
google_analytics: G-CEDD9NZJKK
